name: Python package
run-name: "#${{github.run_number}} : ${{ github.ref }}"

on:
  workflow_dispatch:
    inputs:
    INPUT_VAR:
      description: "dummy input var"
      default: 'masterrrr'
      required: true
      type: string
  push:

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 6
      - name: Install dependencies
        run: |
          echo lalala

      - run: echo $SHA
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}
      - run: echo $SHA
        env:
          SHA: ${{ env.SHA }}

      - name: Printing action parameters
        shell: cmd
        run: |
          #!Printing action parameters
          echo GITHUB_SHA: {{$GITHUB_SHA}}
          echo GITHUB_SHA_SHORT: $REVISION_ID
          echo ACTIONS_BRANCH: ${{ github.action }}#%ACTIONS_BRANCH%
          echo github.action_path: ${{ github.action_path }}
          echo github.action_ref: ${{ github.action_ref }}
          echo github.action_repository: ${{ github.action_repository }}
          echo github.actor: ${{ github.actor }}
          echo github.ref_name: ${{ github.ref_name }}
          echo github.action: ${{ github.action }}
          echo github.workflow: ${{ github.workflow }}
