name: Python package
run-name: "#${{github.run_number}} : ${{ github.ref_name }}"

on:
  workflow_dispatch:
    inputs:
      RUN_QA_INTEGRATION_TESTS:
        description: "dummy"
        default: false
        required: true
        type: boolean
  push:

env:
  RUN_QA_INTEGRATION_TESTS: ${{ inputs.RUN_QA_INTEGRATION_TESTS || github.event_name != 'workflow_dispatch' || 'false'}}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          echo github.event_name = ${{ github.event_name }}

      - name: Printing action parameters
        run: |
          #!Printing action parameters
          echo inputs.RUN_QA_INTEGRATION_TESTS: ${{inputs.RUN_QA_INTEGRATION_TESTS}}

      - name: Print the input name to STDOUT
        run: echo The username is ${{ env.RUN_QA_INTEGRATION_TESTS }} 2. $RUN_QA_INTEGRATION_TESTS 3. env.RUN_QA_INTEGRATION_TESTS !
