name: Python package
run-name: "#${{github.run_number}} : ${{github.ref_name}}"

on:
  workflow_dispatch:
    inputs:
    INPUT_VAR:
      description: "dummy input var"
      default: 'masterrrr'
      required: true
      type: string
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          echo lalala

      - name: Set env
        run: echo "GITHUB_SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Test
        run: echo $GITHUB_SHA_SHORT

      - name: Printing action parameters
        run: |
          #!Printing action parameters
          echo GITHUB_SHA: {{$GITHUB_SHA}}
          echo GITHUB_SHA_SHORT: {{$GITHUB_SHA_SHORT}}
          echo ACTIONS_BRANCH: ${{ github.action }}#%ACTIONS_BRANCH%
          echo github.action_path: ${{ github.action_path }}
          echo github.action_ref: ${{ github.action_ref }}
          echo github.action_repository: ${{ github.action_repository }}
          echo github.actor: ${{ github.actor }}
          echo github.ref_name: ${{ github.ref_name }}
          echo github.action: ${{ github.action }}
          echo github.workflow: ${{ github.workflow }}