name: Python package
run-name: "#${{github.run_number}} : ${{ github.ref }}"

on:
  workflow_dispatch:
    inputs:
      INPUT_VAR:
        description: "dummy"
        default: false
        required: true
        type: boolean
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          echo lalala

      - name: Printing action parameters
        run: |
          #!Printing action parameters
          echo inputs.INPUT_VAR: {{$inputs.INPUT_VAR}}

      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.INPUT_VAR }}
  test:
    needs: build
    if: ${{ inputs.INPUT_VAR == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Install dependencies
        run: |
          echo lalala test
